python/Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from polls import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pools/', include('polls.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('',views.index),
    path('<int:req_page>/', views.index),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

python/Blog/polls/urls.py
from django.urls import path, include
from rest_framework import routers
from rest_framework.urlpatterns import format_suffix_patterns
from . import views, apiviews

# router = routers.DefaultRouter()
# router.register(r'coments', views.CommentViewSet)

urlpatterns = [
    path('', views.index, name='index'),
    path('get/<int:content_id>', views.dynamic, name='dynamic'),
    path('post_dt/', views.update_post, name='update_post'),
    path('create_post/', views.create_new_post, name='create_new_post'),
    path('create_post_panel/', views.create_new_post_panel, name='create_new_post_panel'),
    path('get/<int:content_id>/edit/', views.edit_full_post, name='edit'),
    path('get/<int:content_id>/delete/', views.delete_post, name='delete_post'),
    path('api/', apiviews.CommentList.as_view(), name='comment_list'),
    path('api/get/<int:pk>', apiviews.CommentDetail.as_view(), name='comment_detail'),
    path('users/', apiviews.UserList.as_view()),
    path('users/<int:pk>/', apiviews.UserDetail.as_view()),
    path('upload/',apiviews.Upload_File.as_view()),
    ]
urlpatterns = format_suffix_patterns(urlpatterns)
urlpatterns += [
    path('api-auth/', include('rest_framework.urls')),
]

python/Blog/polls/models.py
from django.db import models
from django.utils import timezone
import datetime


class Comment(models.Model):
    Owner = models.ForeignKey('auth.User', related_name='snippets', on_delete=models.CASCADE, null=True)
    Title = models.CharField(max_length=200)
    Pub_date = models.DateTimeField('date published', auto_now_add=True)
    Emb_html = models.CharField(max_length=2024, null=True, blank=True)
    Content = models.TextField(default='Empty')
    File = models.FileField(upload_to='media/uploads/',  null=True, blank=True)
    Image = models.ImageField(upload_to='media/pic_folder', default='media/None/no-img.jpg')
    Ip_log = models.GenericIPAddressField(null=True)
    User_agent = models.CharField(max_length=200,null=True)

    def image_tag(self):
        return mark_safe('<img src="/polls/pic_folder/%s" width="150" height="150" />' % (self.image))

    image_tag.short_description = 'Image'

    def __str__(self):
        return self.Title

    def was_published_recently(self):
        return self.Pub_date >= timezone.now() - datetime.timedelta(days=1)

python/Blog/polls/forms.py
from django import forms
from .models import *


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['Title', 'Emb_html', 'Content', 'File', 'Image' ]

python/Blog/polls/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.utils import timezone
from .models import Comment
from .forms import CommentForm
import datetime


def index(request, req_page=0):
    dt=datetime.datetime.now()
    item_ct = Comment.objects.count()
    page_count = int(item_ct / 5)
    latest_comment_list = Comment.objects.order_by('-Pub_date')[req_page*5:(req_page*5)+5]
    context = {'latest_cmt_list': latest_comment_list,
               'request': request,
               'page_count': page_count+1,
               'current_page': req_page,
               'next_page': req_page+1,
               }
    dt2=datetime.datetime.now()
    print(dt2-dt)
    print(datetime.datetime.now())
    return render(request, 'index.html', context)


def dynamic(request, content_id):
    try:
        cmt=Comment.objects.get(pk=content_id)
    except:
        raise Http404("Not Found")

    if request.user.is_authenticated:
        context = {'cmt': cmt,'user': request.user, 'auth_user': True}
        return render(request, 'details.html', context)
    else:
        context = {'cmt': cmt, 'auth_user': False}
        return render(request, 'details.html', context)


def update_post(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            print(request.POST)
            post_id = request.POST.get('post_id')
            post_data = request.POST.get('update_post')
            try:
                cmt = Comment.objects.get(pk=int(post_id))
                cmt.Content = post_data
                cmt.save(update_fields=['Content'])
                context={'cmt': cmt.id}
            except Comment.DoesNotExist:
                return HttpResponse(status=500)

        return render(request, 'post.html', context)
    else:
        return HttpResponse('Unauthorized', status=401)


def create_new_post(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = CommentForm(request.POST, request.FILES)
            if form.is_valid():
                form=form.save(commit=False)
                form.Owner = request.user
                form.Ip_log = request.META['REMOTE_ADDR']
                form.User_agent = request.META['HTTP_USER_AGENT']
                form.save()
                item_ct=Comment.objects.count()
                return redirect('/')
            else:
                return HttpResponse('Form is not valid')
        else:
            return HttpResponse('Http Method ERROR')
    else:
        return HttpResponse('Unauthorized, Yetkin yok :D', status=401)


def create_new_post_panel(request):
    form = CommentForm()
    return render(request, 'create.html', {'form': form})


def edit_full_post(request, content_id):
    if not request.user.is_authenticated:
        return HttpResponse('Unauthorized, Yetkin Yok :D', status=401)
    cmt = Comment.objects.get(pk=int(content_id))
    if request.method == 'POST':
        form=CommentForm(request.POST, request.FILES, instance=cmt)
        if form.is_valid():
            cmt = form.save(commit=False)
            cmt.Pub_date = timezone.now()
            cmt.Ip_log = request.META['REMOTE_ADDR']
            cmt.User_agent = request.META['HTTP_USER_AGENT']
            cmt.save()
            return redirect('/pools/get/'+str(cmt.id))
        else:
            return HttpResponse("Form is not valid!")
    else:
        form=CommentForm(instance=cmt)
        if cmt.File:
            print("file var")
            file_url=cmt.File.url
            return render(request,'edit_post.html', {'form': form, 'cmt': cmt, 'file': file_url})
        else:
            return render(request,'edit_post.html', {'form': form, 'cmt': cmt, 'file': '#'})


def delete_post(request,content_id):
    if not request.user.is_authenticated:
        return HttpResponse('Unauthorized, Yetkin Yok :D', status=401)
    cmt = Comment.objects.get(pk=content_id)
    if request.method == 'GET':
        return render(request, 'delete_post.html', {'cmt': cmt})
    elif request.method == 'POST':
        check_again = request.POST.get('ask_yes')
        if check_again == str(check_again).lower() == 'yes':
            cmt.delete()
            return redirect('/')
        else:
            return HttpResponse("Please write yes to delete!")
    else:
        return HttpResponse('Http method error')

python/Blog/polls/templates/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>create_new_post</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/media/css/bootstrap.min.css">
    <script src="/media/js/jquery.min.js"></script>
    <script src="/media/js/bootstrap.min.js"></script>
    <style>
        body{ background: rgba(102, 51, 0, 0.3);}
    </style>

</head>
<body>
<div class="jumbotron text-center">
  <h1>Create New Post</h1>
  <p>You can add more post at here</p>
</div>
<div class="col-md-4 col-md-offset-4">
    <form action="/pools/create_post/" method="post" id="create_post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" send="" class="btn btn-success" value="Submit">
    </form>
</div>
</body>
</html>

python/Blog/polls/templates/delete_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete_post</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/media/css/bootstrap.min.css">
    <script src="/media/js/jquery.min.js"></script>
    <script src="/media/js/bootstrap.min.js"></script>
    <style>
        body{ background: rgba(102, 51, 0, 0.3);}
    </style>
</head>
<body>
<div class="jumbotron text-center">
  <h1>DELETE POST</h1>
  <p>Are you sure?</p>
</div>
<div class="col-md-4 col-md-offset-4">
    <form action="/pools/get/{{cmt.id}}/delete/" method="post" id="delete_post" enctype="multipart/form-data">
        {% csrf_token %}
        <p><label for="ask_yes">Type yes to delete:</label> <input type="text" name="ask_yes" value="" maxlength="200" required="" id="ask_yes"></p>
        <input type="submit" send="" class="btn btn-success" value="Submit">
    </form>
</div>
</body>
</html>

python/Blog/polls/templates/details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Details</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/media/css/bootstrap.min.css">
    <script src="/media/js/jquery.min.js"></script>
    <script src="/media/js/bootstrap.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
    <style>
        body{
            background: rgba(102, 51, 0, 0.3);
            }
        img {
            max-width: 100%;
            height: auto;
            }
        .header {
            border: 1px solid black;
            padding: 15px;
            text-align: center;
            }
        .content{
            border: 1px solid black;
            padding: 25px;
            }
    </style>
</head>
<i>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Myblog</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>

      <li><a href="#">About</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        {% if request.user.is_authenticated %}
            <li><a href="/accounts/logout/"><span class="glyphicon glyphicon-log-in"></span>Logout</a></li>
            <li><a href="/pools/create_post_panel/">Create New Post</a></li>
        {%else%}
            <li><a href="/accounts/login/"><span class="glyphicon glyphicon-log-in"></span>Login</a></li>
        {%endif%}
    </ul>
  </div>
</nav>
{% if cmt %}
    <div class="header">
        <b>{{cmt.Title}}</b>
        <p>{{cmt.Pub_date}}</p>
    </div>
    <div class="content">
        <i><p>{% autoescape off %}{{cmt.Content}}{% endautoescape %}</p></i>
        {% block content %}
        {%if cmt.Image == 'media/None/no-img.jpg'%}
            <img src="{{cmt.Image.url}}" width="50" height="25" alt="{{cmt.Image}}">
        {%else%}
            <img src="{{cmt.Image.url}}" width="640" height="360" alt="{{cmt.Image}}">
    </div>
    {%endif%}
    {% endblock %}
    <p>{% autoescape off %}{{cmt.Emb_html}}{% endautoescape %}</p>
{%else%}
    <b>not found</b>
{%endif%}
<hr>
{% if auth_user%}

<a href="/pools/get/{{cmt.id}}/edit" class="btn btn-success">Edit this Post</a>
<a href="/pools/get/{{cmt.id}}/delete/" class="btn btn-danger">Delete this Post</a>
<hr>

<a href="/accounts/logout/">logout</a>
{%else%}
    <a href="/accounts/login/">Login to edit </a>
{%endif%}
</body>
</html>

python/Blog/polls/templates/edit_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit_post</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/media/css/bootstrap.min.css">
    <script src="/media/js/jquery.min.js"></script>
    <script src="/media/js/bootstrap.min.js"></script>
    <style>
        body{ background: rgba(102, 51, 0, 0.3);}
    </style>

</head>
<body>
<div class="jumbotron text-center">
  <h1>Edit the Post</h1>
  <p>You can edit Post</p>
</div>
<div class="col-md-4 col-md-offset-4">
    <p>This post edited by {{cmt.Ip_log}} -> {{cmt.User_agent}}</p>
    <form action="/pools/get/{{cmt.id}}/edit/" method="post" id="edit_post" enctype="multipart/form-data">
        {% csrf_token %}
        <p><label for="id_Title">Title:</label> <input type="text" name="Title" value="{{cmt.Title}}" maxlength="200" required="" id="id_Title"></p>
        <p><label for="id_Emb_html">Emb html:</label> <input type="text" name="Emb_html" value="{{cmt.Emb_html}}" maxlength="2024" required="" id="id_Emb_html"></p>
        <p><label for="id_Content">Content:</label> <textarea name="Content" cols="40" rows="10" required="" id="id_Content">{{cmt.Content}}</textarea></p>
        <p><label for="id_File">File:</label> <input type="file" name="File" id="id_File"> Old File:<a href="{{file}}">{{file}}</a></p>
        <p><label for="id_Image">Image:</label> <input type="file" name="Image" accept="image/*" id="id_Image">Old Image:<a href="{{cmt.Image.url}}">{{cmt.Image.url}}</a> </p>
        <input type="submit" send="" class="btn btn-success" value="Submit">
    </form>
</div>

</body>
</html>

python/Blog/polls/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="/media/css/bootstrap.min.css">
    <script src="/media/js/jquery.min.js"></script>
    <script src="/media/js/bootstrap.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">

    <title>Blog</title>
    <style> body{ background: rgba(102, 51, 0, 0.3);}
            div.Absolute{
                position: absolute;
                width: 50%;
                bottom: 10px;
                border: 1px solid #8AC007;}
           div.Box{
                border: 1px solid;
                padding: 15px;
                box-shadow: 5px 5px #888888;}
           div.Newpostbox{
               border: 1px solid;
               padding: 10px;}
               .ortala {
               margin-left: 10%;
               margin-right:10%;}
   </style>
</head>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Myblog</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>

      <li><a href="#">About</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        {% if request.user.is_authenticated %}
            <li><a href="/accounts/logout/"><span class="glyphicon glyphicon-log-in"></span>Logout</a></li>
            <li><a href="/pools/create_post_panel/">Create New Post</a></li>
        {%else%}
            <li><a href="/accounts/login/"><span class="glyphicon glyphicon-log-in"></span>Login</a></li>
        {%endif%}
    </ul>
  </div>
</nav>
{% if latest_cmt_list %}
    <ul>
    {% for comment in latest_cmt_list %}
        <div class="Box">
        <li><a href="/pools/get/{{ comment.id }}">{{ comment.Title }}</a></li>

        <p>{{comment.Pub_date}}</p>
        </div>

    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
<hr>
<div class="ortala">
    {% block content %}
    {% if not current_page == 0 %}
    <a href="/{{current_page | add:'-1'}}"> << </a>
    {%endif%}
    {{next_page}}of page{{page_count}}
    <a href="/{{next_page}}"> >> </a>
    {% endblock %}
</div>
<hr>
<p>User:{{request.user}}</p>
<p></p>
</body>
</html>

python/Blog/polls/templates/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>post</title>
</head>
<body>

<p>Ok</p>
<a href="/pools/get/{{cmt}}" >return to post</a>
</body>
</html>